---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  This template will deploy the services required to run an application
  using GitHub as Code repository, AWS CodePipeline and AWS CodeBuild to
  Build and Deploy, And AWS ECS Fargate and AWS ALB.

Parameters:
  LaunchType:
    Type: String
    Default: Fargate
    AllowedValues:
      - Fargate

  GitHubUser:
    Type: String
    Description: Your username in GitHub.

  GitHubRepo:
    Type: String
    Default: timeoff-management-application
    Description: repository of the application.

  GitHubBranch:
    Type: String
    Default: master
    Description: branch of the repository for CD.

  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub token from developer settings.

  TemplateBucket:
    Type: String
    Default: cd-aws-cloudformation-ecs
    Description: bucket for the templates.

Metadata:
  AWS::CloudFormation::Interface:
    ParatemerLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal GitHub Token"
      LaunchType:
        default: "Launch Type"
    ParametersGroups:
      - Label:
          default: Cluster configuration
        Parameters:
          - LaunchType
      - Label:
          default: GitHub configuration
        Parameters:
          - GitHubRepo
          - GitHubUser
          - GitHubToken
          - GitHubBranch
      - Label:
          default: Stack configuration
        Parameters:
          - TemplateBucket

Resources:
  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/ecs-config.yml"
      Parameters:
        LaunchType: !Ref LaunchType
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yml"
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        Service: !GetAtt Service.Outputs.Service
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/load-balancer.yml"
      Parameters:
        LaunchType: !Ref LaunchType
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/vpc.yml"
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.200.0.0/16
        Subnet1CIDR: 10.200.10.0/24
        Subnet2CIDR: 10.200.20.0/24

  Service:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/service.yml"
      Parameters:
        Cluster: !GetAtt Cluster.Outputs.ClusterName
        LaunchType: !Ref LaunchType
        TargetGroup: !GetAtt LoadBalancer.Outputs.TargetGroup
        SourceSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets

Outputs:
  ServiceUrl:
    Description: Service that is being continuously deployed.
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl

  PipelineUrl:
    Description: Continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
